version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coleta
      MYSQL_USER: coleta_user
      MYSQL_PASSWORD: coleta123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  app:
    build: ./python-app
    container_name: coleta_app
    depends_on:
      - mysql
    volumes:
      - ./pcap:/app/pcap
      - ./output:/app/output
    stdin_open: true
    tty: true

